name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Output rust version for educational purposes
        run: rustup --version

      - uses: actions/checkout@v4

      # Libudev Rust Bindings requires `libudev-dev`
      # https://github.com/dcuddeback/libudev-sys
      - name: Install libudev-dev (Linux only)
        run: sudo apt-get install libudev-dev

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Check style
        run: cargo fmt --all --check
        if: contains(matrix.os, 'ubuntu')

      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        if: contains(matrix.os, 'ubuntu')
